services:
  car-booking:
    container_name: car-booking-be
    image: car-booking-be
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      - car-booking-mongo
    expose:
      - '3000'
    ports:
      - '3000:3000'
    env_file:
      - ./.env

  car-booking-mongo:
    container_name: car-booking-mongo
    image: 'mongo'
    expose:
      - '27017'
    ports:
      - '27017:27017'
